@startuml

interface Reader{
    String read()
}

interface Writer{
    int write(String val)
}

class MyDatabase implements Writer{
    - {static} Map<Integer, String> _data;
    - {static} int _count;
    + int write(String inputString)
}

class File implements Writer, Reader{
    String read()
    int write(String val)
}

class Network implements Reader{
    String read()
}

class EncodingModule{
    + EncodingModule(Reader reader, Writer writer)
    + void encode()
}

class EncodingModuleClient{
    + {static} void main(String[] args)
}

EncodingModuleClient --> EncodingModule
EncodingModuleClient --> Reader
EncodingModuleClient --> Writer

EncodingModule --> Writer
EncodingModule --> Reader

@enduml